# THIS IS A ADJUSTMENT OF https://github.com/levilime/ContextProject-Danshal/blob/master/.travis.yml
# ALL HONORS GO TO THE ORIGINAL CREATOR https://github.com/levilime

language: java
# before_install:
# - git clone https://github.com/eishub/tygron.git
# - cd tygron

# install:
# build the connector, testing of the connector is done in the tygron repo CI.
# - mvn -pl "!doc" install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# - java -cp environment/target/tygronenv-*-jar-with-dependencies.jar login.Login $email $password
# - cd ..
# move generated env jar to the same folder as the test file(s)
# - mv tygron/environment/target/tygronenv-*-jar-with-dependencies.jar src/main/goal/nl/tudelft/ti2806/tygronenv-jar-with-dependencies.jar

# make app.properties through travis before script start, needed for user validation
before_script:
# omit tygron version in env name and mas2g env location name
# - sed -i 's tygronenv-*-jar-with-dependencies.jar tygronenv-jar-with-dependencies.jar' src/main/goal/nl/tudelft/ti2806/Tygron.mas2g
- mv src/test/goal/nl/tudelft/ti2806/test.test2g src/main/goal/nl/tudelft/ti2806/test.test2g
- sed -i 's|../../../../../main/goal/nl/tudelft/ti2806/Tygron.mas2g|Tygron.mas2g|g' src/main/goal/nl/tudelft/ti2806/test.test2g
- sed -i 's|../../../../../main/goal/nl/tudelft/ti2806/dummy.pl|dummy.pl|g' src/main/goal/nl/tudelft/ti2806/test.test2g
- sed -i 's|../../../../../main/goal/nl/tudelft/ti2806/Tygron.mod2g|Tygron.mod2g|g' src/main/goal/nl/tudelft/ti2806/test.test2g

script:
# run the Goal Test with a 60s timeout
- timeout 60 java -cp com.github.goalhub.runtime.jar-with-dependencies_*.jar goal.tools.Run src/main/goal/nl/tudelft/ti2806/test.test2g -v > log.txt || echo 0
# print the test output
- cat log.txt
# if there is a test failed then the build fails
- grep "test failed:" log.txt && $? || echo 0
# check that the tests actually passed otherwise the build still fails
- grep "test passed:" log.txt && echo 0 || $?

jdk:
- oraclejdk8